# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, stage ]
  pull_request:
    branches: [ main, stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test
        env: # Or as an environment variable
          front_url: ${{ secrets.FRONT_URL }}
          mongo_db: ${{ secrets.MONGO_DB }}
          mongo_hostname: ${{ secrets.MONGO_HOSTNAME }}
          mongo_password: ${{ secrets.MONGO_PASSWORD }}
          mongo_port: ${{ secrets.MONGO_PORT }}
          mongo_username: ${{ secrets.MONGO_USERNAME }}
          production: ${{ secrets.PRODUCTION }}
          server_port: ${{ secrets.SERVER_PORT }}
          url: ${{ secrets.URL }}
