# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request_target:
    types: [edited, opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test
        env:
          CI: true
          APP_KEY: ${{ secrets.APP_KEY }}
          FRONT_URL: ${{ secrets.FRONT_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_HOSTNAME: ${{ secrets.MONGO_HOSTNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          PRODUCTION: "FALSE"
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          URL: ${{ secrets.URL }}
