# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, stage ]
  pull_request:
    branches: [ main, stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: |
          touch .env
          echo 'APP_KEY: ${{ secrets.APP_KEY }}' >> .env
          echo 'FRONT_URL: ${{ secrets.FRONT_URL }}' >> .env
          echo 'MONGO_DB: ${{ secrets.MONGO_DB }} >>' .env
          echo 'MONGO_HOSTNAME: ${{ secrets.MONGO_HOSTNAME }}' >> .env
          echo 'MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}' >> .env
          echo 'MONGO_PORT: ${{ secrets.MONGO_PORT }}' >> .env
          echo 'MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}' >> .env
          echo 'PRODUCTION: "FALSE"' >> .env
          echo 'SERVER_PORT: ${{ secrets.SERVER_PORT }}' >> .env
          echo 'URL: ${{ secrets.URL }}' >> .env
          npm run test
